### ISSUE TITLE
How to calculate CP/CR/CF1、OP/OR/OF1 ?

### ISSUE THREAD

**Issue by Rmuli** [HCPLab-SYSU/SSGRL#8]
How to calculate CP/CR/CF1、OP/OR/OF1 ?

**Comment by tianshuichen** [comment]
We have presented the definition equations in the paper. Please refer to [our paper](http://openaccess.thecvf.com/content_ICCV_2019/html/Chen_Learning_Semantic-Specific_Graph_Representation_for_Multi-Label_Image_Recognition_ICCV_2019_paper.html) for detailed computing process.

**Comment by Rmuli** [comment]
Thank you very much... I know how to calculate...
