### ISSUE TITLE
The problem about equation (8).

### ISSUE THREAD

**Issue by xiaopingzeng** [HCPLab-SYSU/SSGRL#9]
How to calculate the adjacency matrix in equation (8)? It doesn't say in the paper, but the code does provide a calculated adjacency matrix.

**Comment by xiaopingzeng** [comment]
Sorry, I find the script you give "make_graph.py".

**Comment by zgyangleo** [comment]
> Sorry, I found the script you gave "make_graph.py".

could you solve the problem? i cant find the "make_graph.py", could you share it with me?
